# This program is written bu Dr Tushar Ranjan Moharana. Kindly report bugs to tusharranjanmoharana@gmail.com
# Polarity are calculated as per the GROMOS convention
# Direction to use: run the script from Pymol (File>Run Script) and type "Polar" in the command.
from pymol import cmd
 
def Polar(selection='all'):    
    print (str(selection))
    Polarity = { 'ALL': 0.00, 'N': 0.31, 'C': 0.45, 'O' : 0.45, 'ARG_CD': 0.09, 'ARG_NE': 0.11, 'ARG_CZ': 0.34, 'ARG_NH1': 0.26, 'ARG_NH2': 0.26, 'ASN_CG': 0.29, 'ASN_OD1': 0.45, 'ASN_ND2': 0.72, 'ASP_CG': 0.27, 'ASP_OD1': 0.64, 'ASP_OD2': 0.64, 'CYS_CB': 0.15, 'CYS_SG': 0.37, 'GLN_CD': 0.29, 'GLN_OE1': 0.45, 'GLN_NE2': 0.72, 'GLU_CD': 0.27, 'GLU_OE1': 0.64, 'GLU_OE2': 0.64, 'HIS_ND1': 0.05, 'HIS_NE2': 0.54, 'LYS_CE': 0.13, 'LYS_NZ': 0.13, 'MET_CG': 0.24, 'MET_SD': 0.48, 'MET_CE': 0.24, 'PHE_CD1': 0.14, 'PHE_CD2': 0.14, 'PHE_CE1': 0.14, 'PHE_CE2': 0.14, 'PHE_CZ': 0.14, 'PRO_N': 0.00, 'SER_CB': 0.27, 'SER_OG': 0.67, 'THR_CB': 0.27, 'THR_OG1': 0.67, 'TRP_CG': 0.21, 'TRP_CD1': 0.14, 'TRP_NE1': 0.1, 'TRP_CE3': 0.14, 'TRP_CZ2': 0.14, 'TRP_CZ3': 0.14, 'TRP_CH2': 0.14, 'TYR_CD1': 0.14, 'TYR_CD2': 0.14, 'TYR_CE1': 0.14, 'TYR_CE2': 0.14, 'TYR_CZ': 0.2, 'TYR_OH': 0.61 }
    cmd.set_color('ALL',[float(1-Polarity['ALL']*1.3), float(1-Polarity['ALL']*1.3), float(Polarity['ALL'] + .25)]) # 0.00
    cmd.set_color('N',[float(1-Polarity['N']*1.3), float(1-Polarity['N']*1.3), float(Polarity['N'] + .25)]) 
    cmd.set_color('C',[float(1-Polarity['C']*1.3), float(1-Polarity['C']*1.3), float(Polarity['C'] + .25)]) 
    cmd.set_color('O',[float(1-Polarity['O']*1.3), float(1-Polarity['O']*1.3), float(Polarity['O'] + .25)]) 
    cmd.set_color('ARG_CD',[float(1-Polarity['ARG_CD']*1.3), float(1-Polarity['ARG_CD']*1.3), float(Polarity['ARG_CD'] + .25)]) 
    cmd.set_color('ARG_NE',[float(1-Polarity['ARG_NE']*1.3), float(1-Polarity['ARG_NE']*1.3), float(Polarity['ARG_NE'] + .25)]) 
    cmd.set_color('ARG_CZ',[float(1-Polarity['ARG_CZ']*1.3), float(1-Polarity['ARG_CZ']*1.3), float(Polarity['ARG_CZ'] + .25)]) 
    cmd.set_color('ARG_NH1',[float(1-Polarity['ARG_NH1']*1.3), float(1-Polarity['ARG_NH1']*1.3), float(Polarity['ARG_NH1'] + .25)]) 
    cmd.set_color('ARG_NH2',[float(1-Polarity['ARG_NH2']*1.3), float(1-Polarity['ARG_NH2']*1.3), float(Polarity['ARG_NH2'] + .25)]) 
    cmd.set_color('ASN_CG',[float(1-Polarity['ASN_CG']*1.3), float(1-Polarity['ASN_CG']*1.3), float(Polarity['ASN_CG'] + .25)]) 
    cmd.set_color('ASN_OD1',[float(1-Polarity['ASN_OD1']*1.3), float(1-Polarity['ASN_OD1']*1.3), float(Polarity['ASN_OD1'] + .25)]) 
    cmd.set_color('ASN_ND2',[float(1-Polarity['ASN_ND2']*1.3), float(1-Polarity['ASN_ND2']*1.3), float(Polarity['ASN_ND2'] + .25)]) 
    cmd.set_color('ASP_CG',[float(1-Polarity['ASP_CG']*1.3), float(1-Polarity['ASP_CG']*1.3), float(Polarity['ASP_CG'] + .25)]) 
    cmd.set_color('ASP_OD1',[float(1-Polarity['ASP_OD1']*1.3), float(1-Polarity['ASP_OD1']*1.3), float(Polarity['ASP_OD1'] + .25)]) 
    cmd.set_color('ASP_OD2',[float(1-Polarity['ASP_OD2']*1.3), float(1-Polarity['ASP_OD2']*1.3), float(Polarity['ASP_OD2'] + .25)]) 
    cmd.set_color('CYS_CB',[float(1-Polarity['CYS_CB']*1.3), float(1-Polarity['CYS_CB']*1.3), float(Polarity['CYS_CB'] + .25)]) 
    cmd.set_color('CYS_SG',[float(1-Polarity['CYS_SG']*1.3), float(1-Polarity['CYS_SG']*1.3), float(Polarity['CYS_SG'] + .25)]) 
    cmd.set_color('GLN_CD',[float(1-Polarity['GLN_CD']*1.3), float(1-Polarity['GLN_CD']*1.3), float(Polarity['GLN_CD'] + .25)]) 
    cmd.set_color('GLN_OE1',[float(1-Polarity['GLN_OE1']*1.3), float(1-Polarity['GLN_OE1']*1.3), float(Polarity['GLN_OE1'] + .25)]) 
    cmd.set_color('GLN_NE2',[float(1-Polarity['GLN_NE2']*1.3), float(1-Polarity['GLN_NE2']*1.3), float(Polarity['GLN_NE2'] + .25)]) 
    cmd.set_color('GLU_CD',[float(1-Polarity['GLU_CD']*1.3), float(1-Polarity['GLU_CD']*1.3), float(Polarity['GLU_CD'] + .25)]) 
    cmd.set_color('GLU_OE1',[float(1-Polarity['GLU_OE1']*1.3), float(1-Polarity['GLU_OE1']*1.3), float(Polarity['GLU_OE1'] + .25)]) 
    cmd.set_color('GLU_OE2',[float(1-Polarity['GLU_OE2']*1.3), float(1-Polarity['GLU_OE2']*1.3), float(Polarity['GLU_OE2'] + .25)]) 
    cmd.set_color('HIS_ND1',[float(1-Polarity['HIS_ND1']*1.3), float(1-Polarity['HIS_ND1']*1.3), float(Polarity['HIS_ND1'] + .25)]) 
    cmd.set_color('HIS_NE2',[float(1-Polarity['HIS_NE2']*1.3), float(1-Polarity['HIS_NE2']*1.3), float(Polarity['HIS_NE2'] + .25)]) 
    cmd.set_color('LYS_CE',[float(1-Polarity['LYS_CE']*1.3), float(1-Polarity['LYS_CE']*1.3), float(Polarity['LYS_CE'] + .25)]) 
    cmd.set_color('LYS_NZ',[float(1-Polarity['LYS_NZ']*1.3), float(1-Polarity['LYS_NZ']*1.3), float(Polarity['LYS_NZ'] + .25)]) 
    cmd.set_color('MET_CG',[float(1-Polarity['MET_CG']*1.3), float(1-Polarity['MET_CG']*1.3), float(Polarity['MET_CG'] + .25)]) 
    cmd.set_color('MET_SD',[float(1-Polarity['MET_SD']*1.3), float(1-Polarity['MET_SD']*1.3), float(Polarity['MET_SD'] + .25)]) 
    cmd.set_color('MET_CE',[float(1-Polarity['MET_CE']*1.3), float(1-Polarity['MET_CE']*1.3), float(Polarity['MET_CE'] + .25)]) 
    cmd.set_color('PHE_CD1',[float(1-Polarity['PHE_CD1']*1.3), float(1-Polarity['PHE_CD1']*1.3), float(Polarity['PHE_CD1'] + .25)]) 
    cmd.set_color('PHE_CD2',[float(1-Polarity['PHE_CD2']*1.3), float(1-Polarity['PHE_CD2']*1.3), float(Polarity['PHE_CD2'] + .25)]) 
    cmd.set_color('PHE_CE1',[float(1-Polarity['PHE_CE1']*1.3), float(1-Polarity['PHE_CE1']*1.3), float(Polarity['PHE_CE1'] + .25)]) 
    cmd.set_color('PHE_CE2',[float(1-Polarity['PHE_CE2']*1.3), float(1-Polarity['PHE_CE2']*1.3), float(Polarity['PHE_CE2'] + .25)]) 
    cmd.set_color('PHE_CZ',[float(1-Polarity['PHE_CZ']*1.3), float(1-Polarity['PHE_CZ']*1.3), float(Polarity['PHE_CZ'] + .25)]) 
    cmd.set_color('PRO_N',[float(1-Polarity['PRO_N']*1.3), float(1-Polarity['PRO_N']*1.3), float(Polarity['PRO_N'] + .25)]) 
    cmd.set_color('SER_CB',[float(1-Polarity['SER_CB']*1.3), float(1-Polarity['SER_CB']*1.3), float(Polarity['SER_CB'] + .25)]) 
    cmd.set_color('SER_OG',[float(1-Polarity['SER_OG']*1.3), float(1-Polarity['SER_OG']*1.3), float(Polarity['SER_OG'] + .25)]) 
    cmd.set_color('THR_CB',[float(1-Polarity['THR_CB']*1.3), float(1-Polarity['THR_CB']*1.3), float(Polarity['THR_CB'] + .25)]) 
    cmd.set_color('THR_OG1',[float(1-Polarity['THR_OG1']*1.3), float(1-Polarity['THR_OG1']*1.3), float(Polarity['THR_OG1'] + .25)]) 
    cmd.set_color('TRP_CG',[float(1-Polarity['TRP_CG']*1.3), float(1-Polarity['TRP_CG']*1.3), float(Polarity['TRP_CG'] + .25)]) 
    cmd.set_color('TRP_CD1',[float(1-Polarity['TRP_CD1']*1.3), float(1-Polarity['TRP_CD1']*1.3), float(Polarity['TRP_CD1'] + .25)]) 
    cmd.set_color('TRP_NE1',[float(1-Polarity['TRP_NE1']*1.3), float(1-Polarity['TRP_NE1']*1.3), float(Polarity['TRP_NE1'] + .25)]) 
    cmd.set_color('TRP_CE3',[float(1-Polarity['TRP_CE3']*1.3), float(1-Polarity['TRP_CE3']*1.3), float(Polarity['TRP_CE3'] + .25)]) 
    cmd.set_color('TRP_CZ2',[float(1-Polarity['TRP_CZ2']*1.3), float(1-Polarity['TRP_CZ2']*1.3), float(Polarity['TRP_CZ2'] + .25)]) 
    cmd.set_color('TRP_CZ3',[float(1-Polarity['TRP_CZ3']*1.3), float(1-Polarity['TRP_CZ3']*1.3), float(Polarity['TRP_CZ3'] + .25)]) 
    cmd.set_color('TRP_CH2',[float(1-Polarity['TRP_CH2']*1.3), float(1-Polarity['TRP_CH2']*1.3), float(Polarity['TRP_CH2'] + .25)]) 
    cmd.set_color('TYR_CD1',[float(1-Polarity['TYR_CD1']*1.3), float(1-Polarity['TYR_CD1']*1.3), float(Polarity['TYR_CD1'] + .25)]) 
    cmd.set_color('TYR_CD2',[float(1-Polarity['TYR_CD2']*1.3), float(1-Polarity['TYR_CD2']*1.3), float(Polarity['TYR_CD2'] + .25)]) 
    cmd.set_color('TYR_CE1',[float(1-Polarity['TYR_CE1']*1.3), float(1-Polarity['TYR_CE1']*1.3), float(Polarity['TYR_CE1'] + .25)]) 
    cmd.set_color('TYR_CE2',[float(1-Polarity['TYR_CE2']*1.3), float(1-Polarity['TYR_CE2']*1.3), float(Polarity['TYR_CE2'] + .25)]) 
    cmd.set_color('TYR_CZ',[float(1-Polarity['TYR_CZ']*1.3), float(1-Polarity['TYR_CZ']*1.3), float(Polarity['TYR_CZ'] + .25)]) 
    cmd.set_color('TYR_OH',[float(1-Polarity['TYR_OH']*1.3), float(1-Polarity['TYR_OH']*1.3), float(Polarity['TYR_OH'] + .25)])          
    cmd.color("ALL")
    cmd.color("N","(name n)")
    cmd.color("C","(name c)")
    cmd.color("O","(name o)")
    cmd.color("ARG_CD","(resn arg and name cd)")
    cmd.color("ARG_NE","(resn arg and name ne)")
    cmd.color("ARG_CZ","(resn arg and name cz)")
    cmd.color("ARG_NH1","(resn arg and name nh1)")
    cmd.color("ARG_NH2","(resn arg and name nh2)")
    cmd.color("ASN_CG","(resn asn and name cg)")
    cmd.color("ASN_OD1","(resn asn and name od1)")
    cmd.color("ASN_ND2","(resn asn and name nd2)")
    cmd.color("ASP_CG","(resn asp and name cg)")
    cmd.color("ASP_OD1","(resn asp and name od1)")
    cmd.color("ASP_OD2","(resn asp and name od2)")
    cmd.color("CYS_CB","(resn cys and name cb)")
    cmd.color("CYS_SG","(resn cys and name sg)")
    cmd.color("GLN_CD","(resn gln and name cd)")
    cmd.color("GLN_OE1","(resn gln and name oe1)")
    cmd.color("GLN_NE2","(resn gln and name ne2)")
    cmd.color("GLU_CD","(resn glu and name cd)")
    cmd.color("GLU_OE1","(resn glu and name oe1)")
    cmd.color("GLU_OE2","(resn glu and name oe2)")
    cmd.color("HIS_ND1","(resn his and name nd1)")
    cmd.color("HIS_NE2","(resn his and name ne2)")
    cmd.color("LYS_CE","(resn lys and name ce)")
    cmd.color("LYS_NZ","(resn lys and name nz)")
    cmd.color("MET_CG","(resn met and name cg)")
    cmd.color("MET_SD","(resn met and name sd)")
    cmd.color("MET_CE","(resn met and name ce)")
    cmd.color("PHE_CD1","(resn phe and name cd1)")
    cmd.color("PHE_CD2","(resn phe and name cd2)")
    cmd.color("PHE_CE1","(resn phe and name ce1)")
    cmd.color("PHE_CE2","(resn phe and name ce2)")
    cmd.color("PHE_CZ","(resn phe and name cz)")
    cmd.color("PRO_N","(resn pro and name n)")
    cmd.color("SER_CB","(resn ser and name cb)")
    cmd.color("SER_OG","(resn ser and name og)")
    cmd.color("THR_CB","(resn thr and name cb)")
    cmd.color("THR_OG","(resn thr and name og)")
    cmd.color("TRP_CG","(resn trp and name cg)")
    cmd.color("TRP_CD1","(resn trp and name cd1)")
    cmd.color("TRP_CE3","(resn trp and name ce3)")
    cmd.color("TRP_NE1","(resn trp and name ne1)")
    cmd.color("TRP_CZ2","(resn trp and name cz2)")
    cmd.color("TRP_CZ3","(resn trp and name cz3)")
    cmd.color("TRP_CH2","(resn trp and name ch2)")
    cmd.color("TYR_CD1","(resn tyr and name cd1)")
    cmd.color("TYR_CD2","(resn tyr and name cd2)")
    cmd.color("TYR_CE1","(resn tyr and name ce1)")
    cmd.color("TYR_CE2","(resn tyr and name ce2)")
    cmd.color("TYR_CZ","(resn tyr and name cz)")
    cmd.color("TYR_OH","(resn tyr and name oh)")    
        
cmd.extend('Polar',Polar)
